morse_code = {
    "A": [".-", "Morse-Code-Writer-main/SoundFiles/A_morse_code.ogg"],
    "B": ["-...", "Morse-Code-Writer-main/SoundFiles/B_morse_code.ogg"],
    "C": ["-.-.", "Morse-Code-Writer-main/SoundFiles/C_morse_code.ogg"],
    "D": ["-..","Morse-Code-Writer-main/SoundFiles/D_morse_code.ogg"],
    "E": [".","Morse-Code-Writer-main/SoundFiles/E_morse_code.ogg"],
    "F": ["..-.","Morse-Code-Writer-main/SoundFiles/F_morse_code.ogg"],
    "G": ["--.","Morse-Code-Writer-main/SoundFiles/G_morse_code.ogg"],
    "H": ["....","Morse-Code-Writer-main/SoundFiles/H_morse_code.ogg"],
    "I": ["..","Morse-Code-Writer-main/SoundFiles/I_morse_code.ogg"],
    "J": [".---","Morse-Code-Writer-main/SoundFiles/J_morse_code.ogg"],
    "K": ["-.-","Morse-Code-Writer-main/SoundFiles/K_morse_code.ogg"],
    "L": [".-..","Morse-Code-Writer-main/SoundFiles/L_morse_code.ogg"],
    "M": ["--","Morse-Code-Writer-main/SoundFiles/M_morse_code.ogg"],
    "N": ["-.","Morse-Code-Writer-main/SoundFiles/N_morse_code.ogg"],
    "O": ["---","Morse-Code-Writer-main/SoundFiles/O_morse_code.ogg"],
    "P": [".--.","Morse-Code-Writer-main/SoundFiles/P_morse_code.ogg"],
    "Q": ["--.-","Morse-Code-Writer-main/SoundFiles/Q_morse_code.ogg"],
    "R": [".-.","Morse-Code-Writer-main/SoundFiles/R_morse_code.ogg"],
    "S": ["...","Morse-Code-Writer-main/SoundFiles/S_morse_code.ogg"],
    "T": ["-","Morse-Code-Writer-main/SoundFiles/T_morse_code.ogg"],
    "U": ["..-","Morse-Code-Writer-main/SoundFiles/U_morse_code.ogg"],
    "V": ["...-","Morse-Code-Writer-main/SoundFiles/V_morse_code.ogg"],
    "W": [".--","Morse-Code-Writer-main/SoundFiles/W_morse_code.ogg"],
    "X": ["-..-","Morse-Code-Writer-main/SoundFiles/X_morse_code.ogg"],
    "Y": ["-.--","Morse-Code-Writer-main/SoundFiles/Y_morse_code.ogg"],
    "Z": ["--..","Morse-Code-Writer-main/SoundFiles/Z_morse_code.ogg"],
    "1": [".----","Morse-Code-Writer-main/SoundFiles/1_morse_code.ogg"],
    "2": ["..---","Morse-Code-Writer-main/SoundFiles/2_morse_code.ogg"],
    "3": ["...--","Morse-Code-Writer-main/SoundFiles/3_morse_code.ogg"],
    "4": ["....-","Morse-Code-Writer-main/SoundFiles/4_morse_code.ogg"],
    "5": [".....","Morse-Code-Writer-main/SoundFiles/5_morse_code.ogg"],
    "6": ["-....","Morse-Code-Writer-main/SoundFiles/6_morse_code.ogg"],
    "7": ["--...","Morse-Code-Writer-main/SoundFiles/7_morse_code.ogg"],
    "8": ["---..","Morse-Code-Writer-main/SoundFiles/8_morse_code.ogg"],
    "9": ["----.","Morse-Code-Writer-main/SoundFiles/9_morse_code.ogg"],
    "0": ["-----","Morse-Code-Writer-main/SoundFiles/0_morse_code.ogg"],
    ".": [".-.-.-", ],
    ",": ["--..--", ],
    "?": ["..--..",],
    "'": [".----.",],
    "!": ["-.-.--",],
    "/": ["-..-.",],
    "(": ["-.--.",],
    ")": ["-.--.-",],
    "&": [".-...",],
    ":": ["---...",],
    ";": ["-.-.-.",],
    "=": ["-...-",],
    "+": [".-.-.",],
    "-": ["-....-",],
    "_": ["..--.-",],
    "*": [".-..-.",],
    "$": ["...-..-",],
    "@": [".--.-.",]
}